### ISSUE TITLE
regression: 4.2.0 causes "Call retries were exceeded" with a few Docusaurus project

### ISSUE THREAD

**Issue by jamilbk** [webpack-contrib/css-minimizer-webpack-plugin#198]
### Actual Behavior

Upgrading to 4.2.0 causes the `Call retries were exceeded` with a fresh docusaurus project when `npm run build` is used.

4.1.0 does not exhibit this issue.

### Expected Behavior

Css should minimize without issue.

### How Do We Reproduce?

```shell
npx create-docusaurus@latest my-website classic
cd my-website
npm run build
```

Observe the minimizer crash:

```
jamil@mbair:~/tmp/my-website % npm run build

> my-website@0.0.0 build
> docusaurus build

[INFO] [en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 10.52s

● Server █████████████████████████ building (65%) 1/1 entries 1944/1944 dependencies 625/625 modules 0 active




assets/css/styles.45f640f6.css from Css Minimizer plugin
Error: Call retries were exceeded
assets/css/styles.8ef29f8a.css from Css Minimizer plugin
Error: Call retries were exceeded
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

`webpack-cli` not relevant here

**Comment by alexander-akait** [comment]
Weird :confused: I will look at code, anyway if you found workaround/problem feel free to send a PR

**Comment by sylvainbaronnet** [comment]
I got the same issue with 4.2.0, tried different minifier with same result

**Comment by alexander-akait** [comment]
I think the problem in `jest-worker`, we need to check options and API usage

**Comment by danports** [comment]
Can confirm this regression on another project currently using `4.1.0` - builds using `4.2.0` are failing with the same `Call retries were exceeded` error.

**Comment by ttaylor29** [comment]
We are seeing this issue as well on Azure Pipeline. 

Going back to 4.1.0. Will provide an update soon.

**Comment by alexander-akait** [comment]
WIP on this

**Comment by alexander-akait** [comment]
@SimenB Friendly ping, looks like `jest-worker` is broken for standalone usage:

```
Error: Cannot find module 'jest-util'
Require stack:
- /home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _jestUtil (/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js:14:16)
    at execFunction (/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js:173:11)
    at execHelper (/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js:151:5)
    at execMethod (/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js:155:5)
    at MessagePort.messageListener (/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js:59:7)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:689:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/akait/IdeaProjects/untitled/my-website/node_modules/jest-worker/build/workers/threadChild.js'
  ]
}
```

Here usage - https://github.com/facebook/jest/blob/main/packages/jest-worker/src/workers/threadChild.ts#L9, but no in deps https://github.com/facebook/jest/blob/main/packages/jest-worker/package.json#L19

**Comment by alexander-akait** [comment]
Here fix - https://github.com/facebook/jest/pull/13341, but on the `jest` side

**Comment by zakariazuck** [comment]
Hi folks, I've come here for the same reason.
I'm doing some stuff with webpack and this error popped up.

## This is not a fix, but I just went back to the most recent version @4.1.0  .

**Comment by alexander-akait** [comment]
When https://github.com/facebook/jest/pull/13341 was merged and `jest-worker` will released, just update your deps (transitive, i.e. `rm -rf node_modules && npm i`). If there is no reaction, I will downgrade the versions back

**Comment by vgurkov** [comment]
I tried removing the `node_modules`, `package-lock.json` and reinstalling everything. I'm still getting this error. Unfortunately, the project I'm working on is more than 6 years old with many (large) files, so I can't send something reproducible right away. I'll use `4.1.0` for now.

**Comment by jmsche** [comment]
Hi, a new tag was released for jest: https://github.com/facebook/jest/releases/tag/v29.1.2

After upgrading my vendors, the issue disappeared.

I think this issue can be closed :)

**Comment by SimenB** [comment]
Fix was released 40 minutes ago, sorry about the noise!

https://github.com/facebook/jest/releases/tag/v29.1.2

**Comment by SimenB** [comment]
>I think this issue can be closed :)

Minimum version of `jest-worker` should probably be bumped to help consumers

**Comment by sylvainbaronnet** [comment]
I confirm it works now with new jest release. Thanks @alexander-akait

**Comment by NotMyFault** [comment]
Works fine on my end, thanks to everyone who was investigating into a fix!

**Comment by akshaybabloo** [comment]
can we have the minimum version of jest-worker updated here so that the dependabot can catch the update with a minor bump release?

**Comment by SimenB** [comment]
This was fixed by #199, but not released

**Comment by sushitommy** [comment]
I still get this issue with docusaurus, november 2024

**Comment by alexander-akait** [comment]
@sushitommy Can you create a reproducible repository?
